pipeline {
    agent any 
        
    environment {
        CI = 'true'
        HOME = '.'
        
    }
   
            
    stages {
        
        stage('Clone sources') {
        
        steps {
        
        git url: 'https://github.com/nickgulrajani/simple-node-js-react-npm-app/'
                             }
        }
        stage('Build') {
            steps {
            
                sh 'npm install'
            }
        }
        
        
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        
stage('Sonarqube') {
          environment {
            scannerHome = tool 'sonar'
            }
    
        steps {
            sh 'echo "$PATH"'       
            withSonarQubeEnv('sonar') {
            sh "${scannerHome}/bin/sonar-scanner"
        }
    }
}             
        
        
             
        
        
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
