pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
        HOME = '.'
    }
       
            
    stages {
        
        stage('Clone sources') {
        
        steps {
        
        git url: 'https://github.com/nickgulrajani/simple-node-js-react-npm-app/'
                             }
        }
        stage('Build') {
            steps {
            
                sh 'npm install'
            }
        }
        
        stage('Sonarqube') {
          environment {
            scannerHome = tool 'sonar'
            }
        steps {
        withSonarQubeEnv('sonar') {
            sh "${scannerHome}/bin/sonar-scanner"
        }
    }
}             
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
